language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: altcp
  password:
    secure: CtAWMGM05k2KWrf7Ss9OXfT0P//WELnjd5UwyY79w8u+JVSm3UAHCCgSyg4/AHdoHlMA/bYQOi66P10VrYTjhaLze2cnH9gMJDsHAyIuQa4USnJUSqJ2eWewLm9kY1YJMGoUdT/+wF2zmjp+wdMuoveuL8AsUb+JJMjRaj52jIgA+bHjatbz7iBaVlDh0z9vwK8lDg4pydfAJh/dO4k8utLCwkgzvjQwIFoh0s8ntxHGe7gn567rurjWDdPLtsHEpA+iqxXcOLT8bwawvogQZEU3r7RI52yckulIYdni2RA43PDsOcP/H/E/xX9WZ1zTRxokF6HZlkHzqB53sU8laXR4gswOx2ZTDqbLfUEjoD440lvFP6b0dyFqf05j33XxdByLQR3xZ/SU4YYI4xej5Z12HjKeziDSfA9XzJA6HUSWaZnY1POCLuelTq5T/tJhGSnUEK1THxJdEo7APb0GXVHaZBfMHmdsZ8IHGvwNt58RdFqgU9EJRMSEMbiUJY2fp3RCKvWsvTRJ8BVSkwXt1P6WG2pkdCHAmDXcP/10RDP2q/F280gwPwLXYOw7iMmJxDYOi14UzEPN/w9ATlqxYjgHZ9/1UB6YvHT3O/nURTbwanFjOdkXBEPv3tr49GTo6syV4lyMGDa8c94bBFdSxMcFhdApukmHeftCynEDiks=
  on:
    tags: true
    repo: altcp/gdemandfcast
    python: 3.8
